name: CI - Integration and E2E tests

on: [pull_request]

jobs:
  run-int-e2e-tests:
    name: Run Integration and E2E tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRES_USENAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: projectdb

    # definir os passos necessarios para baixar o app e rodar os testes
    steps:
      - uses: actions/checkout@v3 # baixar o codigo do app no ubuntu

      - uses: actions/setup-node@v3 # configurar o nodeJs
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci # installar as dependencias sem interação

      - run: npx prisma generate --schema ./src/shared/infra/database/prisma/schema.prisma
        env:
          DATABASE_URL: postgresql://postgres:docker@localhost:5432/projectdb?schema=public

      - run: npm run test:int
        env:
          PORT: 3333
          NODE_ENV: test
          JWT_SECRE: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_USL: postgresql://postgres:docker@localhost:5432/projectdb?schema=public

      - run: npm run test:e2e
        env:
          PORT: 3333
          NODE_ENV: test
          JWT_SECRE: fake_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_USL: postgresql://postgres:docker@localhost:5432/projectdb?schema=public
